version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8099:3000"
    volumes:
      - ~/local-gpt/files:/app/files
    environment:
      - DB_DATABASE=mongodb://mongo-admin:P%40ssW0rd@db:27017/local-gpt?authSource=admin
    networks:
      - local-gpt
  db:
    build: ./mongodb
    ports:
      - "27890:27017"
    volumes:
      - ~/local-gpt/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-admin
      - MONGO_INITDB_ROOT_PASSWORD=P@ssW0rd
    restart: always
    networks:
      - local-gpt

networks:
  local-gpt:
